version: "3.5"
services:
  database:
    image: postgres:12.2-alpine
    ports:
      - 5432:5432
    environment:
      # Default master(root) username and password (use it to create more users)
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    networks:
      - n-rtcomm
    volumes:
      # Volume has to be created externally prior to building the app since Docker can't create a shared folder on Windows.
      # Type in command prompt:
      # > docker volume create v-rtcomm-db
      - v-rtcomm-db:/var/lib/postgresql/data
  application:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - 8080:8080
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - n-rtcomm
    depends_on:
      - database
networks:
  # Network has to be created externally prior to building the app.
  # Type in command prompt:
  # > docker network create n-rtcomm
  n-rtcomm:
volumes:
  v-rtcomm-db:
    external: true
